### ISSUE TITLE
CO2.js Integration

### ISSUE THREAD

**Issue by headlesshorse** [overbrowsing/co2-shield#1]
CO2 Shield needs to be based on [CO2.js](https://github.com/thegreenwebfoundation/co2.js/). I was hoping we could configure it to target a specific URL, e.g. for pruner.js, where it would be ideal to simply select the URL for pruner.min.js. Currently, the current example on GitHub pulls from Beacon, but they won’t allow you to measure the size of a specific URL like pruner.min.js.

**Comment by printerscanner** [comment]
I think here it wont make sense to target specific files but it does make sense to target different pages. so like `www.printerscanner.net/blog` or similar. 

Just looking at the code here, do you want to be relying on beacon as a intermediary? This can be done simply with custom code, it just requires some server side calculations which requires a little code.

**Comment by headlesshorse** [comment]
We've decided to stay using Digital Beacon for the data.
